server:
  port: 8081

spring:
  application:
    name: camel-producer
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

# Cluster Configuration (minimal for testing)
cluster:
  name: camel-cluster-test
  node:
    id: producer-test-1
    type: producer
  hazelcast:
    port: 5701
    members:
      - localhost:5701

camel:
  springboot:
    name: camel-producer-test-context

# Producer-specific Configuration
producer:
  order:
    interval: 5000  # Generate orders every 5 seconds for testing
  file:
    interval: 15000 # Generate files every 15 seconds for testing

# File paths
shared:
  file:
    path: shared/input

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,routes
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.example: DEBUG
    org.apache.camel: INFO
    com.hazelcast: WARN
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [${cluster.node.id}] %logger{36} - %msg%n" 